Test new if statement

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -2,15 +2,17 @@ name: Build and Push Database Exporter
 
 on:
   push:
-    tags:
-      - "*.*.*-*"
+    branches:
+      - ekw/gh-actions/release
+#    tags:
+#      - "*.*.*-*"
 
 env:
   UBUNTU_VERSION: '22.04'
   RUST_IMAGE_TAG: '1.73.0'
   S3_BUCKET: s3://eur2ccd.concordium.com
-  OUTFILE: "s3://eur2ccd.concordium.com/concordium-eur2ccd_${{ github.ref_name }}_amd64.deb"
-  IAM_ROLE: "arn:aws:iam::192549843005:role/github_eur2ccd"
+  OUTFILE: "s3://eur2ccd.concordium.com/concordium-eur2ccd_0.6.1-0" #${{ github.ref_name }}_amd64.deb"
+  IAM_ROLE: "arn:aws:iam::192549843005:role/github_eur2ccd" 
 
 permissions:
   id-token: write
@@ -24,7 +26,7 @@ jobs:
       - name: Get the eur2ccd version
         env:
           TAG: ${{ github.ref_name }}
-        run: echo "EUR2CCD_VERSION=${TAG%%-*}" >> $GITHUB_ENV
+        run: eco EUR2CCD_VERSION="0.6.1-0" >> GITHUB_ENV #echo "EUR2CCD_VERSION=${TAG%%-*}" >> $GITHUB_ENV
 
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -52,8 +54,9 @@ jobs:
       - name: Check if version exist in s3
         run: |
           totalFoundObjects=$(aws s3 ls "${{env.OUTFILE}}" --summarize | grep "Total Objects: " | sed "s/[^0-9]*//g")
-          if [ "$totalFoundObjects" -ne "0" ]; then
-              echo "error: ${{env.OUTFILE}} already exists"
+          ec=$?
+          if [ $ec -nq "1" ]; then
+              echo "error: ${{env.OUTFILE}} already exists" or you do not have access.
               exit 1
           fi
 
@@ -66,4 +69,4 @@ jobs:
 
       - name: Publish
         run: |
-          aws s3 cp concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}_amd64.deb ${{ env.OUTFILE }} 
+#          aws s3 cp concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}_amd64.deb ${{ env.OUTFILE }} 
